---
# tasks file for ansible-coreos-kubelet
- name: Create install dir
  become: yes
  file: path={{coreos_kubelet_install_dir}} state=directory mode=0755

- name: Create manifest dir
  become: yes
  file: path={{etc_kubernetes}} state=directory mode=0755

- name: Copy kubelet config
  become: yes
  template: src=kubelet-config.yaml dest={{etc_kubernetes}}/kubelet-config.yaml mode=0755
  notify: reload systemd

- name: Copy kubelet-wrapper.sh
  become: yes
  copy: src=kubelet-wrapper.sh dest={{coreos_kubelet_install_dir}}/kubelet-wrapper.sh mode=0755

- name: Install kubelet-wrapper
  become: yes
  template: src=kubelet-wrapper dest={{coreos_kubelet_install_dir}}/kubelet-wrapper mode=0755

- name: Create env.d dir
  become: yes
  file: path=/etc/env.d state=directory mode=0755

- name: Create kube env file
  become: yes
  template: src=kube.env.j2 dest=/etc/env.d/kube.env
  notify: Create env file

- name: Install kubelet service
  template: src=kubelet.service dest={{coreos_kubelet_systemd}}/kubelet.service
  become: yes
  notify: reload systemd

- name: Start kubelet
  become: yes
  service: name=kubelet.service state=started enabled=yes
